root_dir = "."

[os.unix]
dev = [
    """
    DEBUG=1 TEST=0 \
    ./mvnw clean package && \
    ./mvnw function:run \
    --quantity=1000 \
    --info="Additional information for QR code" \
    --size=500x500 \
    --url="https://example.com" \
    --format="pdf"
    """
]

[os.windows]
dev = []

[exclude]
dir = [".git"]
file = []
ext = ["toml"]
