root_dir = "."

[os.unix]
dev = ["DEBUG=1 TEST=0 ./mvnw clean package && java -jar target/qrgen-0.0.1-SNAPSHOT.jar --quantity=1000"]

[os.windows]
dev = []

[exclude]
dir = [".git"]
file = []
ext = ["toml"]
