root_dir = "."

[os.unix]
dev = [
    """
    DEBUG=1 TEST=0 \
    ./mvnw clean package -q && \
    java -jar target/qrgen-0.0.1-SNAPSHOT.jar \
    --quantity=1000 \
    --info="Additional information for QR code" \
    --size=500 \
    --url="https://example.com" \
    --format="pdf"
    """
]

test = ["./mvnw test"]


[os.windows]
dev = []

[exclude]
dir = [".git"]
file = []
ext = ["toml"]
