package com.pesira.traceability.service;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.pesira.traceability.helpers.Context;
import com.pesira.traceability.model.QRCodeModel;
import com.pesira.traceability.repository.QRCodeRepository;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.imageio.ImageIO;

class PDFGenService {

    private static final float DEFAULT_QRCODE_SIZE = 500; // 500px
    private static final QRCodeRepository qrCodeRepository = new QRCodeRepository();
    private static final String BASE_URL = "https://www.pesira.io/traceability/";
    private static final Long DISTRIBUTOR_ID = 18L;

    public static void generatePDF(
            int idx,
            String projectName,
            Long projectId,
            List<String> qrCodes,
            List<String> logos,
            float size,
            String partner,
            String location,
            String folderName) throws DocumentException, IOException, WriterException {
        // Create pdf file
        Document document = new Document(PageSize.A4);
        String fileName = "QR_codes_" + partner + "_" + idx + ".pdf";
        Path pdfPath = Paths.get(folderName, fileName);

        PdfWriter.getInstance(document, Files.newOutputStream(pdfPath));
        document.open();

        // Add metadata
        document.addTitle("QR Code Batch - " + projectName);
        document.addCreator("Pesira Product Traceability System");
        document.addCreationDate();

        // Add header
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
        Paragraph title = new Paragraph(projectName + " - QR Code Batch", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(15f);
        document.add(title);

        // generate and add QR code images
        Paragraph images = addQRCodeImages(qrCodes, logos, size, partner, location, projectId);
        document.add(images);

        // Add footer
        Font footerFont = new Font(Font.FontFamily.HELVETICA, 7, Font.ITALIC);
        Paragraph footer = new Paragraph(
                "Generated by Pesira Product Traceability System - " + projectName,
                footerFont);

        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(10f);
        document.add(footer);

        document.close();
    }

    private static Paragraph addQRCodeImages(
            List<String> qrCodes,
            List<String> logos,
            float size,
            String partner,
            String location,
            Long projectId) throws IOException, BadElementException, WriterException {
        Paragraph paragraph = new Paragraph();

        List<QRCodeModel> qrCodeBatch = new ArrayList<>();

        String formattedPartner = partner.strip().replace(" ", "_").toLowerCase();

        for (String qrCode : qrCodes) {
            byte[] qrCodeImage = generateQRCodeImage(qrCode, size, logos, formattedPartner);
            com.itextpdf.text.Image qrImage = com.itextpdf.text.Image.getInstance(qrCodeImage);
            float fitSize = (size / DEFAULT_QRCODE_SIZE) * 100;
            qrImage.scaleToFit(fitSize, fitSize);

            if (Context.DEBUG.greaterThanOrEqual(2))
                System.out.println("QR code image generated successfully: " + qrCode);

            Chunk chunk = new Chunk(qrImage, 3, 3, true);
            paragraph.add(chunk);
            // Add spacing after each image
            paragraph.add(new Chunk(" "));

            // Add successfully generated QR codes to the batch;
            QRCodeModel qr = new QRCodeModel(qrCode, projectId, location, DISTRIBUTOR_ID);
            if (Context.DEBUG.greaterThanOrEqual(2)) {
                System.out.println(qr);
            }
            qrCodeBatch.add(qr);
        }

        // Add QR batch to the database
        if (Context.DEBUG.equalsValue(0)) {
            qrCodeRepository.batchInsert(qrCodeBatch);
        }

        return paragraph;
    }

    private static byte[] generateQRCodeImage(String qrCode, float size, List<String> logos, String partner)
            throws WriterException, IOException {
        Map<EncodeHintType, Object> hints = new HashMap<>();
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M);
        hints.put(EncodeHintType.MARGIN, 2);

        int canvasSize = (int) size;

        int qrSize = (int) (canvasSize * 0.6);

        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        BitMatrix bitMatrix = qrCodeWriter.encode(BASE_URL + qrCode, BarcodeFormat.QR_CODE, qrSize, qrSize, hints);
        BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(bitMatrix);

        int borderSize = 10;
        BufferedImage canvas = new BufferedImage(
                canvasSize + borderSize,
                canvasSize + borderSize,
                BufferedImage.TYPE_INT_RGB);

        Graphics2D graphics = canvas.createGraphics();
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Add canvas border
        graphics.setColor(Color.BLACK);
        graphics.setStroke(new BasicStroke(borderSize));
        graphics.drawRect(0, 0, canvasSize - borderSize, canvasSize - borderSize);

        // Set background color
        graphics.setColor(Color.WHITE);
        graphics.fillRect(5, 5, canvasSize, canvasSize);

        // Draw QR code in the center
        int qrPos = (canvasSize - qrSize) / 2;
        graphics.drawImage(qrImage, qrPos, qrPos, null);

        // Draw logos
        if (logos != null && logos.size() > 0) {
            double maxWidth = canvasSize * 0.3;
            double maxHeight = canvasSize * 0.2;

            int posId = 1;
            for (String path : logos) {
                int lPosX, lPosY;
                BufferedImage logo = ImageIO.read(new File(path));
                int originalWidth = logo.getWidth();
                int originalHeight = logo.getHeight();

                double scaleFactor = Math.min(maxWidth / originalWidth, maxHeight / originalHeight);

                int logoWidth = (int) (originalWidth * scaleFactor);
                int logoHeight = (int) (originalHeight * scaleFactor);

                // Set logos
                switch (posId) {
                    case 1: // Top right
                        lPosX = 10;
                        lPosY = 10;
                        posId++;
                        break;
                    case 2: // Top left
                        lPosX = canvasSize - logoWidth - 10;
                        lPosY = 10;
                        posId++;
                        break;
                    case 3: // Bottom left
                        lPosX = 10;
                        lPosY = canvasSize - logoHeight - 10;
                        posId++;
                        break;
                    case 4: // Bottom right
                        lPosX = canvasSize - logoWidth - 10;
                        lPosY = canvasSize - logoHeight - 10;
                        posId++;
                        break;
                    default:
                        lPosX = 0;
                        lPosY = 0;
                        break;
                }

                Image scaledLogo = logo.getScaledInstance(logoWidth, logoHeight, Image.SCALE_SMOOTH);
                graphics.drawImage(scaledLogo, lPosX, lPosY, logoWidth, logoHeight, null);
            }
        }

        // Add QR code value
        graphics.setColor(Color.BLACK);
        graphics.setFont(new java.awt.Font("Helvetica", Font.NORMAL, 16));

        int textWidth = qrCode.length() * 8;
        int textPosX = (canvasSize - textWidth) / 2;
        int textPosY = qrPos + qrSize + 10;
        graphics.drawString(qrCode, textPosX, textPosY);

        // Add QR code label
        String label = String.format("SK-%s", partner);
        int labelWidth = label.length() * 8;
        int labelPosX = (canvasSize - labelWidth) / 2;
        int labelPosY = qrPos + qrSize + 35;
        graphics.drawString(label, labelPosX, labelPosY);

        // Add test label
        if (Context.TEST.equalsValue(1)) {
            graphics.setColor(Color.RED);
            graphics.setFont(new java.awt.Font("Helvetica", Font.BOLD, 50));

            String test = "TEST";
            int testPosX = 90;
            int testPosY = qrPos + qrSize - 50;
            graphics.rotate(Math.toRadians(-90), testPosX, testPosY);
            graphics.drawString(test, testPosX, testPosY);
        }

        graphics.dispose();

        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        ImageIO.write(canvas, "PNG", bytes);

        return bytes.toByteArray();
    }
}
